image: intro2ros

stages:
    - build
    - evaluate
    
build:
  stage: build
  tags:
    - intro2ros
  script:
    - source /opt/ros/noetic/setup.bash
    - ./build.sh
  artifacts: 
      paths: 
        - git-repos
        - catkin_ws
      expire_in: 30 minutes
  

exercise2a:
  stage: evaluate
  tags:
    - intro2ros
  script:
    - source /opt/ros/noetic/setup.bash
    - cd catkin_ws
    - source devel/setup.bash
    - roslaunch --nodes agitr_chapter6 randvelturtlesim.launch
  dependencies:
    - build

exercise2b:
  stage: evaluate
  tags:
    - intro2ros
  script:
    - source /opt/ros/noetic/setup.bash
    - cd catkin_ws
    - source devel/setup.bash
    - roslaunch --nodes agitr_chapter6 randvelturtlesim2.launch
  dependencies:
    - build

exercise2c:
  stage: evaluate
  tags:
    - intro2ros
  script:
    - source /opt/ros/noetic/setup.bash
    - cd catkin_ws
    - source devel/setup.bash
    - roslaunch --nodes agitr_chapter6 teleopturtlesim4.launch
  dependencies:
    - build

lint:
  stage: evaluate
  tags:
    - intro2ros
  script:
    - source /opt/ros/noetic/setup.bash
    - catkin_lint git-repos
  dependencies:
    - build
